### ISSUE TITLE
Final step: set up DocSearch!

### ISSUE THREAD

**Issue by tesseralis** [reactjs/bg.reactjs.org#39]
Congrats on almost completing the core pages! One of the final steps is to change the [DocSearch API key](https://github.com/reactjs/es.reactjs.org/blob/ed07fa53dc9ab7950e630900f7da3a7c821d63a6/src/components/LayoutHeader/DocSearch.js#L25).

One of the maintainers needs to [sign up for DocSearch](https://community.algolia.com/docsearch/#join-docsearch-program)

**Comment by jumpalottahigh** [comment]
I signed up for the service, they do mention that it could take up to a few days. Will add the API key when I get it.

**Comment by jumpalottahigh** [comment]
@tesseralis Up dated in https://github.com/reactjs/bg.reactjs.org/commit/d3d4fe84ca5d2c55cb8aebcf12953a5edd76ed91
